name = "DecisionDomains"
uuid = "b3c2c752-e935-440e-b739-2b15001bb599"
authors = ["Mel Krusniak <mel.krusniak@vanderbilt.edu>", "Jackson Wagner <jackson.wagner-1@colorado.edu>", "Kyle Wray <k.wray@northeastern.edu>", "Zachary Sunberg <zachary.sunberg@colorado.edu>", "Tyler Becker <tyler.becker-1@colorado.edu>"]
version = "0.0.1"

[deps]
DecisionNetworks = "a1ae968e-b3ba-4546-81a6-f6e3d3a9391a"
DecisionProblems = "b716e576-a1f9-415a-b454-baf909aed799"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
RockSample = "de008ff0-c357-11e8-3329-7fe746fe836e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[sources]
DecisionNetworks = {path = "../DecisionNetworks.jl"}
DecisionProblems = {path = "../DecisionProblems.jl"}

[compat]
Distributions = "0.25.122"
LazySets = "5.0.0"
POMDPTools = "1.1.0"
POMDPs = "1.0.0"
RockSample = "0.2.1"
StaticArrays = "1.9.15"
name = "DecisionDomains"
uuid = "b3c2c752-e935-440e-b739-2b15001bb599"
authors = ["Mel Krusniak <mel.krusniak@vanderbilt.edu>", "Jackson Wagner <jackson.wagner-1@colorado.edu>", "Kyle Wray <k.wray@northeastern.edu>", "Zachary Sunberg <zachary.sunberg@colorado.edu>", "Tyler Becker <tyler.becker-1@colorado.edu>"]
version = "0.0.1"

[deps]
DecisionNetworks = "a1ae968e-b3ba-4546-81a6-f6e3d3a9391a"
DecisionProblems = "b716e576-a1f9-415a-b454-baf909aed799"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RockSample = "de008ff0-c357-11e8-3329-7fe746fe836e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[sources]
DecisionNetworks = {path = "../DecisionNetworks.jl"}
DecisionProblems = {path = "../DecisionProblems.jl"}

[compat]
Distributions = "0.25.122"
POMDPTools = "1.1.0"
POMDPs = "1.0.0"
Random = "1.11.0"
RockSample = "0.2.1"
StaticArrays = "1.9.15"
